default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Siphose1
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_blog_app_development

test:
  <<: *default
  database: my_blog_app_test

production:
  <<: *default
  database: my_blog_app_production
  username: my_blog_app
  password: <%= ENV["MY_BLOG_APP_DATABASE_PASSWORD"] %>
